easy_admin:
    site_name: 'Sublylo'
    user:
        display_name: true
    entities:
        # List the entity class name you want to manage
        - App\Entity\Product
        - App\Entity\Category
        - App\Entity\Tag
        - App\Entity\User
